name: Publish to PyPI

on:
  release:
    types: [created]

# Add permissions for trusted publishing
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine wheel
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Update version
      run: |
        # Extract version from the GitHub release tag (e.g., v1.0.3 -> 1.0.3)
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "Publishing version $VERSION"
        # Update version in pyproject.toml
        sed -i "s/version = \"[0-9]*\.[0-9]*\.[0-9]*\"/version = \"$VERSION\"/" pyproject.toml
        # Update version in qcmd_cli/__init__.py
        sed -i "s/__version__ = \"[0-9]*\.[0-9]*\.[0-9]*\"/__version__ = \"$VERSION\"/" qcmd_cli/__init__.py
    - name: Build package
      run: |
        # Create empty requirements.txt if it doesn't exist
        if [ ! -f requirements.txt ]; then
          touch requirements.txt
        fi
        python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }} 